# Generated by Django 4.1.6 on 2023-02-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=60)),
                ('priority', models.CharField(blank=True, choices=[(None, 'Please Choose'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
